// Differences Between Arrays and Pointers
/*There are several differences between the use of arrays and the use of pointers to arrays.
In this section, we will use the vector array and pv pointer as defined below:*/
int main()
{
    int vector[5] = {1, 2, 3, 4, 5};
    int *pv = vector;
    /*The code generated by vector[i] is different from the code generated by vector+i.
    The notation vector[i] generates machine code that starts at location vector, moves
    i positions from this location, and uses its content. The notation vector+i generates
    machine code that starts at location vector, adds i to the address, and then uses the
    contents at that address. While the result is the same, the generated machine code is
    different. This difference is rarely of significance to most programmers.*/

    /*There is a difference when the sizeof operator is applied to an array and to a pointer
    to the same array. Applying the sizeof operator to vector will return 20, the number
    of bytes allocated to the array. Applying the sizeof operator against pv will return 4,
    the pointer’s size.
    */

    /*The pointer pv is an lvalue. An lvalue denotes the term used on the lefthand side of
    an assignment operator. An lvalue must be capable of being modified. An array name
    such as vector is not an lvalue and cannot be modified. The address assigned to an
    array cannot be changed . A pointer can be assigned a new value and reference a different
    section of memory.
    */

    // Consider the following:
    pv = pv + 1;
    vector = vector + 1; // Syntax error
    /*We cannot modify vector, only its contents. However, the expression vector+1 is fine,
    as demonstrated below:*/
    pv = vector + 1;
}